version: '3'
services:
  app:
    container_name: senfreelance
    restart: always
    build: .
    ports:
      - '8080:5000'
    links:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
