apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: senefreelance.dev
      http:
        paths:
          - path: /api/users/?(.*)
            backend:
              serviceName: auth-srv
              servicePort: 5000
          - path: /api/freelancers/?(.*)
            backend:
              serviceName: freelancers-srv
              servicePort: 5000
          - path: /api/orders/?(.*)
            backend:
              serviceName: orders-srv
              servicePort: 5000
          - path: /api/payments/?(.*)
            backend:
              serviceName: payments-srv
              servicePort: 5000
